
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_HOST:3306}/lesson_user?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: 12345678

mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰映射