server:
  port: ${SERVER_PORT:9192}

message-service:
  host: ${MESSAGE_SERVICE_HOST:localhost}
  port: ${MESSAGE_SERVICE_PORT:9090}

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/lesson_user?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: 12345678
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰映射